In [20]:
import os
import sys
import io
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [53]:
df_matrix_train = pd.read_csv("C:/2019/The Port/FoodFlix/food-com-recipes-and-user-interactions/interactions_train.csv")
len(df_matrix_train)
# 698901


698901

In [54]:
df_matrix_test= pd.read_csv("C:/2019/The Port/FoodFlix/food-com-recipes-and-user-interactions/interactions_test.csv")
len(df_matrix_test)

12455

In [55]:
df_matrix_test

user_id  recipe_id        date  rating      u       i
0         8937      44551  2005-12-23     4.0      2  173538
1        56680     126118  2006-10-07     4.0     16  177847
2       349752     219596  2008-04-12     0.0     26   89896
3       628951      82783  2007-11-13     2.0     45  172637
4        92816     435013  2013-07-31     3.0     52  177935
5       280271     228179  2007-07-29     5.0     55  178179
6       345569     186470  2008-10-05     0.0     57  177482
7       724516     298748  2011-05-07     5.0     71  177749
8       176615     118119  2006-10-27     0.0     82  178250
9        56112     166712  2007-08-02     5.0     89  177821
10      537179      78641  2009-11-20     4.0     91  177805
11      222478     437144  2010-11-09     5.0     97  178178
12       22898      65976  2003-12-14     5.0    101  173681
13      857489     311630  2009-09-20     5.0    120  178097
14     1056692     312579  2013-08-31     4.0    122  177486
15       89831      74778  2006-01-14     5.0    130  178228
16      107583     141156  2008-12-20     5.0    141  178186
17      461834     479953  2013-04-08     5.0    143  177720
18      148715      99695  2004-09-23     5.0    150  173783
19     1206102     207099  2014-01-05     5.0    152  178117
20      213139     366693  2010-04-19     4.0    159  178159
21      128541      50194  2008-11-14     5.0    163  177808
22      865936     221247  2009-11-09     5.0    165  178180
23      592157      80001  2008-06-04     5.0    166  175826
24      323186     482126  2012-08-14     5.0    172  178192
25      585496     173241  2008-10-12     4.0    173  146887
26      320449     282862  2008-02-16     4.0    174  143653
27      220348     394419  2009-11-25     5.0    179  178249
28     2324285     484976  2013-04-15     4.0    181  177773
29      459426     223667  2008-04-10     4.0    183  167455
...        ...        ...         ...     ...    ...     ...
12425   358714     355968  2009-10-19     5.0  24942  145512
12426   779986     371990  2009-05-19     5.0  24943  108042
12427   297321     130956  2006-05-01     5.0  24946  117529
12428  1277979      85390  2009-08-28     5.0  24951  174038
12429   268515     146774  2005-12-08     3.0  24968  148475
12430   302170     159156  2006-03-26     3.0  24972  111730
12431  2452031     407164  2013-04-18     5.0  24981  148973
12432   494258     205039  2007-05-27     4.0  24982  141583
12433   869163     251787  2008-06-22     5.0  24984  128229
12434   557416     249840  2007-10-25     5.0  25006  167315
12435   218411     384881  2009-08-23     2.0  25008  135179
12436   587445     251480  2008-11-30     3.0  25009  129282
12437  1519155     333907  2010-04-27     4.0  25012  144218
12438  1342637     249735  2009-08-12     5.0  25014  153073
12439  1562890     192558  2011-03-21     4.0  25020  118960
12440  1248947      14944  2009-05-20     5.0  25024  120008
12441   178696      94391  2005-02-21     5.0  25025  145197
12442  1727796     275273  2010-11-12     5.0  25026  169640
12443    29997     203749  2007-07-06     4.0  25030  173470
12444   471682     156257  2007-05-06     5.0  25032  159458
12445   541949     175116  2007-09-08     2.0  25033  125465
12446  1248602     299886  2013-12-14     4.0  25041  133351
12447  1724643     375807  2011-11-08     5.0  25047  154459
12448   937528     375371  2010-01-06     5.0  25048  157275
12449   472815     187829  2011-10-31     0.0  25051  147807
12450   101053     179011  2009-01-03     5.0  25054  130258
12451   252205      81398  2005-12-26     2.0  25055  152255
12452   624305     142984  2011-01-15     1.0  25057  139864
12453   173575     104842  2004-12-18     3.0  25059  140646
12454  1249650     287280  2009-04-28     4.0  25070  166028

[12455 rows x 6 columns]

In [56]:
df_matrix_train_ranked = df_matrix_train.sort_values(by='rating', ascending=False)

In [57]:
# Later used for mapping 
ranked_recipe_id = df_matrix_train_ranked['recipe_id']

In [58]:
df_matrix_train = df_matrix_train.sort_values(by='u').drop(columns='user_id').drop(columns='recipe_id').drop(columns='date')
df_matrix_test = df_matrix_test.sort_values(by='u').drop(columns='user_id').drop(columns='recipe_id').drop(columns='date')

In [59]:
df_matrix_train_array = df_matrix_train.to_numpy()
df_matrix_test_array = df_matrix_test.to_numpy()

In [60]:
len(df_matrix_test_array)

12455

In [61]:
from sklearn.cluster import KMeans

In [62]:
kmeans = KMeans(n_clusters=9, random_state=0).fit(df_matrix_train_array)

In [63]:
x= df_matrix_test_array[0].reshape(1, -1)
x

array([[4.00000e+00, 2.00000e+00, 1.73538e+05]])

In [82]:
# Trying to parse a dataset in kmeans.predict instead of one value to predict clusters for multiple people
y = []
for i in range(12455):
    y.append(df_matrix_test_array[i].reshape(1,-1))
    
len(y)

12455

In [83]:
# Converting list to array
df_matrix_test_array_reshaped = np.asarray(y)

In [84]:
kmeans.predict(x)


array([7])

In [86]:
# kmeans.predict(df_matrix_test_array_reshaped)

In [32]:
kmeans.cluster_centers_

array([[4.57111162e+00, 3.55013768e+03, 1.03789022e+04],
       [4.57608696e+00, 4.41099503e+03, 1.10421992e+05],
       [4.58130727e+00, 4.39939683e+03, 1.48901104e+05],
       [4.56968395e+00, 4.41983763e+03, 5.19482609e+04],
       [4.56058574e+00, 4.34895064e+03, 1.29816315e+05],
       [4.57161097e+00, 4.41704579e+03, 9.15927356e+04],
       [4.57458815e+00, 4.32805357e+03, 3.17996565e+04],
       [4.58965458e+00, 4.15704577e+03, 1.68315499e+05],
       [4.57368326e+00, 4.29943328e+03, 7.19832053e+04]])

In [33]:
kmeans.labels_

array([8, 8, 0, ..., 7, 7, 2])

In [61]:
kmeans.inertia_ 

903101394.9472222

In [34]:
kmeans.n_iter_

17

In [35]:
# Finding out recipes ids in the same cluster

In [36]:
# Suggesting the ids 

In [38]:
# The user will interact with a UI - picture/name - which has recipe id embedded in it - 
#  rating, user id, recipe id is passed to predict - the cluster
# Random dish id from that cluster are suggested ( just one? )
# this dish id is mapped to a picture and a name and displayed.

In [88]:
# Mapping them to the dish names in the recipes csv  
df_recipes_raw = pd.read_csv("C:/2019/The Port/FoodFlix/food-com-recipes-and-user-interactions/RAW_recipes.csv")

In [89]:
df_recipes_raw['id'][1]

31490

In [99]:
# Matching the ranked dishes with recipes in ranked_recipe_id
arr_ranked_recipe_id =  ranked_recipe_id.head(10).to_numpy()
arr_ranked_recipe_id[1]

53892

In [104]:
df_recipes_raw['id'].isin([4684,  53892, 278225, 359199, 135350, 241252,  94308,  13511,
       227316, 116926])

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
231607    False
231608    False
231609    False
231610    False
231611    False
231612    False
231613    False
231614    False
231615    False
231616    False
231617    False
231618    False
231619    False
231620    False
231621    False
231622    False
231623    False
231624    False
231625    False
231626    False
231627    False
231628    False
231629    False
231630    False
231631    False
231632    False
231633    False
231634    False
231635    False
231636    False
Name: id, Length: 231637